#!/usr/bin/env python
# -*- coding: utf-8 -*-

__mtime__ = '14/03/2018'

import cv2
import numpy as np
def extractValue(imgOriginal):
    height, width, numChannels = imgOriginal.shape

    imgHSV = np.zeros((height, width, 3), np.uint8)

    imgHSV = cv2.cvtColor(imgOriginal, cv2.COLOR_BGR2HSV)

    imgHue, imgSaturation, imgValue = cv2.split(imgHSV)

    return imgValue


img_path = "../test_images/id2.jpg"
img = cv2.imread(img_path)
#img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#img = cv2.threshold(img, 10, 255, cv2.THRESH_BINARY_INV)[1]

gray_img = extractValue(img)
#cv2.namedWindow('a_window')
cv2.imshow('a_window', gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('savedImg.jpg',gray_img)
#cv2.imshow('b_window', img)
print('good')
